package com.mdove.passwordguard.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mdove.passwordguard.greendao.entity.DailySelf;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DAILY_SELF".
*/
public class DailySelfDao extends AbstractDao<DailySelf, Long> {

    public static final String TABLENAME = "DAILY_SELF";

    /**
     * Properties of entity DailySelf.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MContent = new Property(1, String.class, "mContent", false, "M_CONTENT");
        public final static Property MTimeStamp = new Property(2, Long.class, "mTimeStamp", false, "M_TIME_STAMP");
        public final static Property MTvGroup = new Property(3, String.class, "mTvGroup", false, "M_TV_GROUP");
        public final static Property MLabelId = new Property(4, Long.class, "mLabelId", false, "M_LABEL_ID");
        public final static Property MLabelName = new Property(5, String.class, "mLabelName", false, "M_LABEL_NAME");
        public final static Property MIsFavorite = new Property(6, int.class, "mIsFavorite", false, "M_IS_FAVORITE");
        public final static Property MIsHide = new Property(7, Integer.class, "mIsHide", false, "M_IS_HIDE");
    }


    public DailySelfDao(DaoConfig config) {
        super(config);
    }
    
    public DailySelfDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DAILY_SELF\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"M_CONTENT\" TEXT," + // 1: mContent
                "\"M_TIME_STAMP\" INTEGER," + // 2: mTimeStamp
                "\"M_TV_GROUP\" TEXT," + // 3: mTvGroup
                "\"M_LABEL_ID\" INTEGER," + // 4: mLabelId
                "\"M_LABEL_NAME\" TEXT," + // 5: mLabelName
                "\"M_IS_FAVORITE\" INTEGER NOT NULL ," + // 6: mIsFavorite
                "\"M_IS_HIDE\" INTEGER);"); // 7: mIsHide
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DAILY_SELF\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DailySelf entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mContent = entity.getMContent();
        if (mContent != null) {
            stmt.bindString(2, mContent);
        }
 
        Long mTimeStamp = entity.getMTimeStamp();
        if (mTimeStamp != null) {
            stmt.bindLong(3, mTimeStamp);
        }
 
        String mTvGroup = entity.getMTvGroup();
        if (mTvGroup != null) {
            stmt.bindString(4, mTvGroup);
        }
 
        Long mLabelId = entity.getMLabelId();
        if (mLabelId != null) {
            stmt.bindLong(5, mLabelId);
        }
 
        String mLabelName = entity.getMLabelName();
        if (mLabelName != null) {
            stmt.bindString(6, mLabelName);
        }
        stmt.bindLong(7, entity.getMIsFavorite());
 
        Integer mIsHide = entity.getMIsHide();
        if (mIsHide != null) {
            stmt.bindLong(8, mIsHide);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DailySelf entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mContent = entity.getMContent();
        if (mContent != null) {
            stmt.bindString(2, mContent);
        }
 
        Long mTimeStamp = entity.getMTimeStamp();
        if (mTimeStamp != null) {
            stmt.bindLong(3, mTimeStamp);
        }
 
        String mTvGroup = entity.getMTvGroup();
        if (mTvGroup != null) {
            stmt.bindString(4, mTvGroup);
        }
 
        Long mLabelId = entity.getMLabelId();
        if (mLabelId != null) {
            stmt.bindLong(5, mLabelId);
        }
 
        String mLabelName = entity.getMLabelName();
        if (mLabelName != null) {
            stmt.bindString(6, mLabelName);
        }
        stmt.bindLong(7, entity.getMIsFavorite());
 
        Integer mIsHide = entity.getMIsHide();
        if (mIsHide != null) {
            stmt.bindLong(8, mIsHide);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DailySelf readEntity(Cursor cursor, int offset) {
        DailySelf entity = new DailySelf( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // mContent
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // mTimeStamp
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // mTvGroup
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // mLabelId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // mLabelName
            cursor.getInt(offset + 6), // mIsFavorite
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7) // mIsHide
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DailySelf entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMContent(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMTimeStamp(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setMTvGroup(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMLabelId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setMLabelName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setMIsFavorite(cursor.getInt(offset + 6));
        entity.setMIsHide(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DailySelf entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DailySelf entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DailySelf entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
