package com.mdove.passwordguard.greendao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 29): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 29;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        DailyPlanDao.createTable(db, ifNotExists);
        DailySelfDao.createTable(db, ifNotExists);
        DeletedDailySelfDao.createTable(db, ifNotExists);
        DeletedPasswordDao.createTable(db, ifNotExists);
        DeleteSelfTaskDao.createTable(db, ifNotExists);
        GroupInfoDao.createTable(db, ifNotExists);
        MainTodayPlanDao.createTable(db, ifNotExists);
        PasswordDao.createTable(db, ifNotExists);
        SecondSinglePlanDao.createTable(db, ifNotExists);
        SecondTodayPlanDao.createTable(db, ifNotExists);
        SelfTaskDao.createTable(db, ifNotExists);
        SelfTaskLabelDao.createTable(db, ifNotExists);
        SelfTaskTimerDao.createTable(db, ifNotExists);
        SinglePlanDao.createTable(db, ifNotExists);
        SucSelfTaskDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        DailyPlanDao.dropTable(db, ifExists);
        DailySelfDao.dropTable(db, ifExists);
        DeletedDailySelfDao.dropTable(db, ifExists);
        DeletedPasswordDao.dropTable(db, ifExists);
        DeleteSelfTaskDao.dropTable(db, ifExists);
        GroupInfoDao.dropTable(db, ifExists);
        MainTodayPlanDao.dropTable(db, ifExists);
        PasswordDao.dropTable(db, ifExists);
        SecondSinglePlanDao.dropTable(db, ifExists);
        SecondTodayPlanDao.dropTable(db, ifExists);
        SelfTaskDao.dropTable(db, ifExists);
        SelfTaskLabelDao.dropTable(db, ifExists);
        SelfTaskTimerDao.dropTable(db, ifExists);
        SinglePlanDao.dropTable(db, ifExists);
        SucSelfTaskDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(DailyPlanDao.class);
        registerDaoClass(DailySelfDao.class);
        registerDaoClass(DeletedDailySelfDao.class);
        registerDaoClass(DeletedPasswordDao.class);
        registerDaoClass(DeleteSelfTaskDao.class);
        registerDaoClass(GroupInfoDao.class);
        registerDaoClass(MainTodayPlanDao.class);
        registerDaoClass(PasswordDao.class);
        registerDaoClass(SecondSinglePlanDao.class);
        registerDaoClass(SecondTodayPlanDao.class);
        registerDaoClass(SelfTaskDao.class);
        registerDaoClass(SelfTaskLabelDao.class);
        registerDaoClass(SelfTaskTimerDao.class);
        registerDaoClass(SinglePlanDao.class);
        registerDaoClass(SucSelfTaskDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
