package com.mdove.passwordguard.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mdove.passwordguard.greendao.entity.Password;

import com.mdove.passwordguard.greendao.PasswordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig passwordDaoConfig;

    private final PasswordDao passwordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        passwordDaoConfig = daoConfigMap.get(PasswordDao.class).clone();
        passwordDaoConfig.initIdentityScope(type);

        passwordDao = new PasswordDao(passwordDaoConfig, this);

        registerDao(Password.class, passwordDao);
    }
    
    public void clear() {
        passwordDaoConfig.getIdentityScope().clear();
    }

    public PasswordDao getPasswordDao() {
        return passwordDao;
    }

}
