package com.mdove.passwordguard.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mdove.passwordguard.greendao.entity.DeletedPassword;
import com.mdove.passwordguard.greendao.entity.GroupInfo;
import com.mdove.passwordguard.greendao.entity.Password;
import com.mdove.passwordguard.greendao.entity.DailySelf;

import com.mdove.passwordguard.greendao.DeletedPasswordDao;
import com.mdove.passwordguard.greendao.GroupInfoDao;
import com.mdove.passwordguard.greendao.PasswordDao;
import com.mdove.passwordguard.greendao.DailySelfDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig deletedPasswordDaoConfig;
    private final DaoConfig groupInfoDaoConfig;
    private final DaoConfig passwordDaoConfig;
    private final DaoConfig dailySelfDaoConfig;

    private final DeletedPasswordDao deletedPasswordDao;
    private final GroupInfoDao groupInfoDao;
    private final PasswordDao passwordDao;
    private final DailySelfDao dailySelfDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        deletedPasswordDaoConfig = daoConfigMap.get(DeletedPasswordDao.class).clone();
        deletedPasswordDaoConfig.initIdentityScope(type);

        groupInfoDaoConfig = daoConfigMap.get(GroupInfoDao.class).clone();
        groupInfoDaoConfig.initIdentityScope(type);

        passwordDaoConfig = daoConfigMap.get(PasswordDao.class).clone();
        passwordDaoConfig.initIdentityScope(type);

        dailySelfDaoConfig = daoConfigMap.get(DailySelfDao.class).clone();
        dailySelfDaoConfig.initIdentityScope(type);

        deletedPasswordDao = new DeletedPasswordDao(deletedPasswordDaoConfig, this);
        groupInfoDao = new GroupInfoDao(groupInfoDaoConfig, this);
        passwordDao = new PasswordDao(passwordDaoConfig, this);
        dailySelfDao = new DailySelfDao(dailySelfDaoConfig, this);

        registerDao(DeletedPassword.class, deletedPasswordDao);
        registerDao(GroupInfo.class, groupInfoDao);
        registerDao(Password.class, passwordDao);
        registerDao(DailySelf.class, dailySelfDao);
    }
    
    public void clear() {
        deletedPasswordDaoConfig.clearIdentityScope();
        groupInfoDaoConfig.clearIdentityScope();
        passwordDaoConfig.clearIdentityScope();
        dailySelfDaoConfig.clearIdentityScope();
    }

    public DeletedPasswordDao getDeletedPasswordDao() {
        return deletedPasswordDao;
    }

    public GroupInfoDao getGroupInfoDao() {
        return groupInfoDao;
    }

    public PasswordDao getPasswordDao() {
        return passwordDao;
    }

    public DailySelfDao getDailySelfDao() {
        return dailySelfDao;
    }

}
