package com.mdove.passwordguard.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mdove.passwordguard.greendao.entity.LongPlan;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LONG_PLAN".
*/
public class LongPlanDao extends AbstractDao<LongPlan, Long> {

    public static final String TABLENAME = "LONG_PLAN";

    /**
     * Properties of entity LongPlan.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MLongPlan = new Property(1, String.class, "mLongPlan", false, "M_LONG_PLAN");
        public final static Property MIsSuc = new Property(2, int.class, "mIsSuc", false, "M_IS_SUC");
        public final static Property MIsSee = new Property(3, int.class, "mIsSee", false, "M_IS_SEE");
        public final static Property MStartTime = new Property(4, long.class, "mStartTime", false, "M_START_TIME");
        public final static Property MEndTime = new Property(5, long.class, "mEndTime", false, "M_END_TIME");
        public final static Property MTime = new Property(6, long.class, "mTime", false, "M_TIME");
        public final static Property MUrgent = new Property(7, int.class, "mUrgent", false, "M_URGENT");
        public final static Property MImportant = new Property(8, int.class, "mImportant", false, "M_IMPORTANT");
        public final static Property MLabelId = new Property(9, long.class, "mLabelId", false, "M_LABEL_ID");
        public final static Property MLabel = new Property(10, String.class, "mLabel", false, "M_LABEL");
        public final static Property MTips = new Property(11, String.class, "mTips", false, "M_TIPS");
    }


    public LongPlanDao(DaoConfig config) {
        super(config);
    }
    
    public LongPlanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LONG_PLAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"M_LONG_PLAN\" TEXT," + // 1: mLongPlan
                "\"M_IS_SUC\" INTEGER NOT NULL ," + // 2: mIsSuc
                "\"M_IS_SEE\" INTEGER NOT NULL ," + // 3: mIsSee
                "\"M_START_TIME\" INTEGER NOT NULL ," + // 4: mStartTime
                "\"M_END_TIME\" INTEGER NOT NULL ," + // 5: mEndTime
                "\"M_TIME\" INTEGER NOT NULL ," + // 6: mTime
                "\"M_URGENT\" INTEGER NOT NULL ," + // 7: mUrgent
                "\"M_IMPORTANT\" INTEGER NOT NULL ," + // 8: mImportant
                "\"M_LABEL_ID\" INTEGER NOT NULL ," + // 9: mLabelId
                "\"M_LABEL\" TEXT," + // 10: mLabel
                "\"M_TIPS\" TEXT);"); // 11: mTips
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LONG_PLAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LongPlan entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mLongPlan = entity.getMLongPlan();
        if (mLongPlan != null) {
            stmt.bindString(2, mLongPlan);
        }
        stmt.bindLong(3, entity.getMIsSuc());
        stmt.bindLong(4, entity.getMIsSee());
        stmt.bindLong(5, entity.getMStartTime());
        stmt.bindLong(6, entity.getMEndTime());
        stmt.bindLong(7, entity.getMTime());
        stmt.bindLong(8, entity.getMUrgent());
        stmt.bindLong(9, entity.getMImportant());
        stmt.bindLong(10, entity.getMLabelId());
 
        String mLabel = entity.getMLabel();
        if (mLabel != null) {
            stmt.bindString(11, mLabel);
        }
 
        String mTips = entity.getMTips();
        if (mTips != null) {
            stmt.bindString(12, mTips);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LongPlan entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mLongPlan = entity.getMLongPlan();
        if (mLongPlan != null) {
            stmt.bindString(2, mLongPlan);
        }
        stmt.bindLong(3, entity.getMIsSuc());
        stmt.bindLong(4, entity.getMIsSee());
        stmt.bindLong(5, entity.getMStartTime());
        stmt.bindLong(6, entity.getMEndTime());
        stmt.bindLong(7, entity.getMTime());
        stmt.bindLong(8, entity.getMUrgent());
        stmt.bindLong(9, entity.getMImportant());
        stmt.bindLong(10, entity.getMLabelId());
 
        String mLabel = entity.getMLabel();
        if (mLabel != null) {
            stmt.bindString(11, mLabel);
        }
 
        String mTips = entity.getMTips();
        if (mTips != null) {
            stmt.bindString(12, mTips);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public LongPlan readEntity(Cursor cursor, int offset) {
        LongPlan entity = new LongPlan( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // mLongPlan
            cursor.getInt(offset + 2), // mIsSuc
            cursor.getInt(offset + 3), // mIsSee
            cursor.getLong(offset + 4), // mStartTime
            cursor.getLong(offset + 5), // mEndTime
            cursor.getLong(offset + 6), // mTime
            cursor.getInt(offset + 7), // mUrgent
            cursor.getInt(offset + 8), // mImportant
            cursor.getLong(offset + 9), // mLabelId
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // mLabel
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11) // mTips
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LongPlan entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMLongPlan(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMIsSuc(cursor.getInt(offset + 2));
        entity.setMIsSee(cursor.getInt(offset + 3));
        entity.setMStartTime(cursor.getLong(offset + 4));
        entity.setMEndTime(cursor.getLong(offset + 5));
        entity.setMTime(cursor.getLong(offset + 6));
        entity.setMUrgent(cursor.getInt(offset + 7));
        entity.setMImportant(cursor.getInt(offset + 8));
        entity.setMLabelId(cursor.getLong(offset + 9));
        entity.setMLabel(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setMTips(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(LongPlan entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(LongPlan entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(LongPlan entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
