package com.mdove.passwordguard.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mdove.passwordguard.greendao.entity.MainTodayPlan;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MAIN_TODAY_PLAN".
*/
public class MainTodayPlanDao extends AbstractDao<MainTodayPlan, Long> {

    public static final String TABLENAME = "MAIN_TODAY_PLAN";

    /**
     * Properties of entity MainTodayPlan.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MTodayPlan = new Property(1, String.class, "mTodayPlan", false, "M_TODAY_PLAN");
        public final static Property MIsSuc = new Property(2, int.class, "mIsSuc", false, "M_IS_SUC");
        public final static Property MIsSee = new Property(3, int.class, "mIsSee", false, "M_IS_SEE");
        public final static Property MTime = new Property(4, long.class, "mTime", false, "M_TIME");
        public final static Property MUrgent = new Property(5, int.class, "mUrgent", false, "M_URGENT");
        public final static Property MImportant = new Property(6, int.class, "mImportant", false, "M_IMPORTANT");
        public final static Property MLabelId = new Property(7, long.class, "mLabelId", false, "M_LABEL_ID");
        public final static Property MLabel = new Property(8, String.class, "mLabel", false, "M_LABEL");
        public final static Property MTips = new Property(9, String.class, "mTips", false, "M_TIPS");
    }


    public MainTodayPlanDao(DaoConfig config) {
        super(config);
    }
    
    public MainTodayPlanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MAIN_TODAY_PLAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"M_TODAY_PLAN\" TEXT," + // 1: mTodayPlan
                "\"M_IS_SUC\" INTEGER NOT NULL ," + // 2: mIsSuc
                "\"M_IS_SEE\" INTEGER NOT NULL ," + // 3: mIsSee
                "\"M_TIME\" INTEGER NOT NULL ," + // 4: mTime
                "\"M_URGENT\" INTEGER NOT NULL ," + // 5: mUrgent
                "\"M_IMPORTANT\" INTEGER NOT NULL ," + // 6: mImportant
                "\"M_LABEL_ID\" INTEGER NOT NULL ," + // 7: mLabelId
                "\"M_LABEL\" TEXT," + // 8: mLabel
                "\"M_TIPS\" TEXT);"); // 9: mTips
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MAIN_TODAY_PLAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MainTodayPlan entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mTodayPlan = entity.getMTodayPlan();
        if (mTodayPlan != null) {
            stmt.bindString(2, mTodayPlan);
        }
        stmt.bindLong(3, entity.getMIsSuc());
        stmt.bindLong(4, entity.getMIsSee());
        stmt.bindLong(5, entity.getMTime());
        stmt.bindLong(6, entity.getMUrgent());
        stmt.bindLong(7, entity.getMImportant());
        stmt.bindLong(8, entity.getMLabelId());
 
        String mLabel = entity.getMLabel();
        if (mLabel != null) {
            stmt.bindString(9, mLabel);
        }
 
        String mTips = entity.getMTips();
        if (mTips != null) {
            stmt.bindString(10, mTips);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MainTodayPlan entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mTodayPlan = entity.getMTodayPlan();
        if (mTodayPlan != null) {
            stmt.bindString(2, mTodayPlan);
        }
        stmt.bindLong(3, entity.getMIsSuc());
        stmt.bindLong(4, entity.getMIsSee());
        stmt.bindLong(5, entity.getMTime());
        stmt.bindLong(6, entity.getMUrgent());
        stmt.bindLong(7, entity.getMImportant());
        stmt.bindLong(8, entity.getMLabelId());
 
        String mLabel = entity.getMLabel();
        if (mLabel != null) {
            stmt.bindString(9, mLabel);
        }
 
        String mTips = entity.getMTips();
        if (mTips != null) {
            stmt.bindString(10, mTips);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MainTodayPlan readEntity(Cursor cursor, int offset) {
        MainTodayPlan entity = new MainTodayPlan( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // mTodayPlan
            cursor.getInt(offset + 2), // mIsSuc
            cursor.getInt(offset + 3), // mIsSee
            cursor.getLong(offset + 4), // mTime
            cursor.getInt(offset + 5), // mUrgent
            cursor.getInt(offset + 6), // mImportant
            cursor.getLong(offset + 7), // mLabelId
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // mLabel
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // mTips
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MainTodayPlan entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMTodayPlan(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMIsSuc(cursor.getInt(offset + 2));
        entity.setMIsSee(cursor.getInt(offset + 3));
        entity.setMTime(cursor.getLong(offset + 4));
        entity.setMUrgent(cursor.getInt(offset + 5));
        entity.setMImportant(cursor.getInt(offset + 6));
        entity.setMLabelId(cursor.getLong(offset + 7));
        entity.setMLabel(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setMTips(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MainTodayPlan entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MainTodayPlan entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MainTodayPlan entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
