package com.mdove.passwordguard.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mdove.passwordguard.greendao.entity.Schedule;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SCHEDULE".
*/
public class ScheduleDao extends AbstractDao<Schedule, Long> {

    public static final String TABLENAME = "SCHEDULE";

    /**
     * Properties of entity Schedule.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MSchedule = new Property(1, String.class, "mSchedule", false, "M_SCHEDULE");
        public final static Property MIsSuc = new Property(2, int.class, "mIsSuc", false, "M_IS_SUC");
        public final static Property MIsSee = new Property(3, int.class, "mIsSee", false, "M_IS_SEE");
        public final static Property MTime = new Property(4, long.class, "mTime", false, "M_TIME");
        public final static Property MUrgent = new Property(5, int.class, "mUrgent", false, "M_URGENT");
        public final static Property MImportant = new Property(6, int.class, "mImportant", false, "M_IMPORTANT");
        public final static Property MLabelId = new Property(7, long.class, "mLabelId", false, "M_LABEL_ID");
        public final static Property MLabel = new Property(8, String.class, "mLabel", false, "M_LABEL");
        public final static Property MTips = new Property(9, String.class, "mTips", false, "M_TIPS");
        public final static Property StartHour = new Property(10, int.class, "startHour", false, "START_HOUR");
        public final static Property StartMin = new Property(11, int.class, "startMin", false, "START_MIN");
        public final static Property EndHour = new Property(12, int.class, "endHour", false, "END_HOUR");
        public final static Property EndMin = new Property(13, int.class, "endMin", false, "END_MIN");
        public final static Property SucStartHour = new Property(14, int.class, "sucStartHour", false, "SUC_START_HOUR");
        public final static Property SucStartMin = new Property(15, int.class, "sucStartMin", false, "SUC_START_MIN");
        public final static Property SucEndHour = new Property(16, int.class, "sucEndHour", false, "SUC_END_HOUR");
        public final static Property SucEndMin = new Property(17, int.class, "sucEndMin", false, "SUC_END_MIN");
    }


    public ScheduleDao(DaoConfig config) {
        super(config);
    }
    
    public ScheduleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SCHEDULE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"M_SCHEDULE\" TEXT," + // 1: mSchedule
                "\"M_IS_SUC\" INTEGER NOT NULL ," + // 2: mIsSuc
                "\"M_IS_SEE\" INTEGER NOT NULL ," + // 3: mIsSee
                "\"M_TIME\" INTEGER NOT NULL ," + // 4: mTime
                "\"M_URGENT\" INTEGER NOT NULL ," + // 5: mUrgent
                "\"M_IMPORTANT\" INTEGER NOT NULL ," + // 6: mImportant
                "\"M_LABEL_ID\" INTEGER NOT NULL ," + // 7: mLabelId
                "\"M_LABEL\" TEXT," + // 8: mLabel
                "\"M_TIPS\" TEXT," + // 9: mTips
                "\"START_HOUR\" INTEGER NOT NULL ," + // 10: startHour
                "\"START_MIN\" INTEGER NOT NULL ," + // 11: startMin
                "\"END_HOUR\" INTEGER NOT NULL ," + // 12: endHour
                "\"END_MIN\" INTEGER NOT NULL ," + // 13: endMin
                "\"SUC_START_HOUR\" INTEGER NOT NULL ," + // 14: sucStartHour
                "\"SUC_START_MIN\" INTEGER NOT NULL ," + // 15: sucStartMin
                "\"SUC_END_HOUR\" INTEGER NOT NULL ," + // 16: sucEndHour
                "\"SUC_END_MIN\" INTEGER NOT NULL );"); // 17: sucEndMin
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SCHEDULE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Schedule entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mSchedule = entity.getMSchedule();
        if (mSchedule != null) {
            stmt.bindString(2, mSchedule);
        }
        stmt.bindLong(3, entity.getMIsSuc());
        stmt.bindLong(4, entity.getMIsSee());
        stmt.bindLong(5, entity.getMTime());
        stmt.bindLong(6, entity.getMUrgent());
        stmt.bindLong(7, entity.getMImportant());
        stmt.bindLong(8, entity.getMLabelId());
 
        String mLabel = entity.getMLabel();
        if (mLabel != null) {
            stmt.bindString(9, mLabel);
        }
 
        String mTips = entity.getMTips();
        if (mTips != null) {
            stmt.bindString(10, mTips);
        }
        stmt.bindLong(11, entity.getStartHour());
        stmt.bindLong(12, entity.getStartMin());
        stmt.bindLong(13, entity.getEndHour());
        stmt.bindLong(14, entity.getEndMin());
        stmt.bindLong(15, entity.getSucStartHour());
        stmt.bindLong(16, entity.getSucStartMin());
        stmt.bindLong(17, entity.getSucEndHour());
        stmt.bindLong(18, entity.getSucEndMin());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Schedule entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mSchedule = entity.getMSchedule();
        if (mSchedule != null) {
            stmt.bindString(2, mSchedule);
        }
        stmt.bindLong(3, entity.getMIsSuc());
        stmt.bindLong(4, entity.getMIsSee());
        stmt.bindLong(5, entity.getMTime());
        stmt.bindLong(6, entity.getMUrgent());
        stmt.bindLong(7, entity.getMImportant());
        stmt.bindLong(8, entity.getMLabelId());
 
        String mLabel = entity.getMLabel();
        if (mLabel != null) {
            stmt.bindString(9, mLabel);
        }
 
        String mTips = entity.getMTips();
        if (mTips != null) {
            stmt.bindString(10, mTips);
        }
        stmt.bindLong(11, entity.getStartHour());
        stmt.bindLong(12, entity.getStartMin());
        stmt.bindLong(13, entity.getEndHour());
        stmt.bindLong(14, entity.getEndMin());
        stmt.bindLong(15, entity.getSucStartHour());
        stmt.bindLong(16, entity.getSucStartMin());
        stmt.bindLong(17, entity.getSucEndHour());
        stmt.bindLong(18, entity.getSucEndMin());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Schedule readEntity(Cursor cursor, int offset) {
        Schedule entity = new Schedule( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // mSchedule
            cursor.getInt(offset + 2), // mIsSuc
            cursor.getInt(offset + 3), // mIsSee
            cursor.getLong(offset + 4), // mTime
            cursor.getInt(offset + 5), // mUrgent
            cursor.getInt(offset + 6), // mImportant
            cursor.getLong(offset + 7), // mLabelId
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // mLabel
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // mTips
            cursor.getInt(offset + 10), // startHour
            cursor.getInt(offset + 11), // startMin
            cursor.getInt(offset + 12), // endHour
            cursor.getInt(offset + 13), // endMin
            cursor.getInt(offset + 14), // sucStartHour
            cursor.getInt(offset + 15), // sucStartMin
            cursor.getInt(offset + 16), // sucEndHour
            cursor.getInt(offset + 17) // sucEndMin
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Schedule entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMSchedule(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMIsSuc(cursor.getInt(offset + 2));
        entity.setMIsSee(cursor.getInt(offset + 3));
        entity.setMTime(cursor.getLong(offset + 4));
        entity.setMUrgent(cursor.getInt(offset + 5));
        entity.setMImportant(cursor.getInt(offset + 6));
        entity.setMLabelId(cursor.getLong(offset + 7));
        entity.setMLabel(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setMTips(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setStartHour(cursor.getInt(offset + 10));
        entity.setStartMin(cursor.getInt(offset + 11));
        entity.setEndHour(cursor.getInt(offset + 12));
        entity.setEndMin(cursor.getInt(offset + 13));
        entity.setSucStartHour(cursor.getInt(offset + 14));
        entity.setSucStartMin(cursor.getInt(offset + 15));
        entity.setSucEndHour(cursor.getInt(offset + 16));
        entity.setSucEndMin(cursor.getInt(offset + 17));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Schedule entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Schedule entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Schedule entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
