package com.mdove.passwordguard.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mdove.passwordguard.greendao.entity.SelfTaskLabel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SELF_TASK_LABEL".
*/
public class SelfTaskLabelDao extends AbstractDao<SelfTaskLabel, Long> {

    public static final String TABLENAME = "SELF_TASK_LABEL";

    /**
     * Properties of entity SelfTaskLabel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MTvLabel = new Property(1, String.class, "mTvLabel", false, "M_TV_LABEL");
        public final static Property MBgColor = new Property(2, String.class, "mBgColor", false, "M_BG_COLOR");
        public final static Property MTimeStamp = new Property(3, Long.class, "mTimeStamp", false, "M_TIME_STAMP");
    }


    public SelfTaskLabelDao(DaoConfig config) {
        super(config);
    }
    
    public SelfTaskLabelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SELF_TASK_LABEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"M_TV_LABEL\" TEXT," + // 1: mTvLabel
                "\"M_BG_COLOR\" TEXT," + // 2: mBgColor
                "\"M_TIME_STAMP\" INTEGER);"); // 3: mTimeStamp
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SELF_TASK_LABEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SelfTaskLabel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mTvLabel = entity.getMTvLabel();
        if (mTvLabel != null) {
            stmt.bindString(2, mTvLabel);
        }
 
        String mBgColor = entity.getMBgColor();
        if (mBgColor != null) {
            stmt.bindString(3, mBgColor);
        }
 
        Long mTimeStamp = entity.getMTimeStamp();
        if (mTimeStamp != null) {
            stmt.bindLong(4, mTimeStamp);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SelfTaskLabel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mTvLabel = entity.getMTvLabel();
        if (mTvLabel != null) {
            stmt.bindString(2, mTvLabel);
        }
 
        String mBgColor = entity.getMBgColor();
        if (mBgColor != null) {
            stmt.bindString(3, mBgColor);
        }
 
        Long mTimeStamp = entity.getMTimeStamp();
        if (mTimeStamp != null) {
            stmt.bindLong(4, mTimeStamp);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SelfTaskLabel readEntity(Cursor cursor, int offset) {
        SelfTaskLabel entity = new SelfTaskLabel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // mTvLabel
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // mBgColor
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // mTimeStamp
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SelfTaskLabel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMTvLabel(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMBgColor(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMTimeStamp(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SelfTaskLabel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SelfTaskLabel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SelfTaskLabel entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
