package com.mdove.passwordguard.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mdove.passwordguard.greendao.entity.SelfTaskTimer;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SELF_TASK_TIMER".
*/
public class SelfTaskTimerDao extends AbstractDao<SelfTaskTimer, Long> {

    public static final String TABLENAME = "SELF_TASK_TIMER";

    /**
     * Properties of entity SelfTaskTimer.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MTask = new Property(1, String.class, "mTask", false, "M_TASK");
        public final static Property MTime = new Property(2, long.class, "mTime", false, "M_TIME");
        public final static Property MStopTime = new Property(3, long.class, "mStopTime", false, "M_STOP_TIME");
        public final static Property MNotificationId = new Property(4, long.class, "mNotificationId", false, "M_NOTIFICATION_ID");
        public final static Property MIsCancel = new Property(5, long.class, "mIsCancel", false, "M_IS_CANCEL");
        public final static Property MIsSuc = new Property(6, int.class, "mIsSuc", false, "M_IS_SUC");
    }


    public SelfTaskTimerDao(DaoConfig config) {
        super(config);
    }
    
    public SelfTaskTimerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SELF_TASK_TIMER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"M_TASK\" TEXT," + // 1: mTask
                "\"M_TIME\" INTEGER NOT NULL ," + // 2: mTime
                "\"M_STOP_TIME\" INTEGER NOT NULL ," + // 3: mStopTime
                "\"M_NOTIFICATION_ID\" INTEGER NOT NULL ," + // 4: mNotificationId
                "\"M_IS_CANCEL\" INTEGER NOT NULL ," + // 5: mIsCancel
                "\"M_IS_SUC\" INTEGER NOT NULL );"); // 6: mIsSuc
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SELF_TASK_TIMER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SelfTaskTimer entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mTask = entity.getMTask();
        if (mTask != null) {
            stmt.bindString(2, mTask);
        }
        stmt.bindLong(3, entity.getMTime());
        stmt.bindLong(4, entity.getMStopTime());
        stmt.bindLong(5, entity.getMNotificationId());
        stmt.bindLong(6, entity.getMIsCancel());
        stmt.bindLong(7, entity.getMIsSuc());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SelfTaskTimer entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mTask = entity.getMTask();
        if (mTask != null) {
            stmt.bindString(2, mTask);
        }
        stmt.bindLong(3, entity.getMTime());
        stmt.bindLong(4, entity.getMStopTime());
        stmt.bindLong(5, entity.getMNotificationId());
        stmt.bindLong(6, entity.getMIsCancel());
        stmt.bindLong(7, entity.getMIsSuc());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SelfTaskTimer readEntity(Cursor cursor, int offset) {
        SelfTaskTimer entity = new SelfTaskTimer( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // mTask
            cursor.getLong(offset + 2), // mTime
            cursor.getLong(offset + 3), // mStopTime
            cursor.getLong(offset + 4), // mNotificationId
            cursor.getLong(offset + 5), // mIsCancel
            cursor.getInt(offset + 6) // mIsSuc
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SelfTaskTimer entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMTask(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMTime(cursor.getLong(offset + 2));
        entity.setMStopTime(cursor.getLong(offset + 3));
        entity.setMNotificationId(cursor.getLong(offset + 4));
        entity.setMIsCancel(cursor.getLong(offset + 5));
        entity.setMIsSuc(cursor.getInt(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SelfTaskTimer entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SelfTaskTimer entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SelfTaskTimer entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
