package com.mdove.passwordguard.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mdove.passwordguard.greendao.entity.SelfTask;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SELF_TASK".
*/
public class SelfTaskDao extends AbstractDao<SelfTask, Long> {

    public static final String TABLENAME = "SELF_TASK";

    /**
     * Properties of entity SelfTask.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MTask = new Property(1, String.class, "mTask", false, "M_TASK");
        public final static Property MTime = new Property(2, long.class, "mTime", false, "M_TIME");
        public final static Property MIsSuc = new Property(3, int.class, "mIsSuc", false, "M_IS_SUC");
        public final static Property MIsSee = new Property(4, int.class, "mIsSee", false, "M_IS_SEE");
        public final static Property MPriority = new Property(5, int.class, "mPriority", false, "M_PRIORITY");
    }


    public SelfTaskDao(DaoConfig config) {
        super(config);
    }
    
    public SelfTaskDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SELF_TASK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"M_TASK\" TEXT," + // 1: mTask
                "\"M_TIME\" INTEGER NOT NULL ," + // 2: mTime
                "\"M_IS_SUC\" INTEGER NOT NULL ," + // 3: mIsSuc
                "\"M_IS_SEE\" INTEGER NOT NULL ," + // 4: mIsSee
                "\"M_PRIORITY\" INTEGER NOT NULL );"); // 5: mPriority
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SELF_TASK\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SelfTask entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mTask = entity.getMTask();
        if (mTask != null) {
            stmt.bindString(2, mTask);
        }
        stmt.bindLong(3, entity.getMTime());
        stmt.bindLong(4, entity.getMIsSuc());
        stmt.bindLong(5, entity.getMIsSee());
        stmt.bindLong(6, entity.getMPriority());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SelfTask entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mTask = entity.getMTask();
        if (mTask != null) {
            stmt.bindString(2, mTask);
        }
        stmt.bindLong(3, entity.getMTime());
        stmt.bindLong(4, entity.getMIsSuc());
        stmt.bindLong(5, entity.getMIsSee());
        stmt.bindLong(6, entity.getMPriority());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SelfTask readEntity(Cursor cursor, int offset) {
        SelfTask entity = new SelfTask( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // mTask
            cursor.getLong(offset + 2), // mTime
            cursor.getInt(offset + 3), // mIsSuc
            cursor.getInt(offset + 4), // mIsSee
            cursor.getInt(offset + 5) // mPriority
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SelfTask entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMTask(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMTime(cursor.getLong(offset + 2));
        entity.setMIsSuc(cursor.getInt(offset + 3));
        entity.setMIsSee(cursor.getInt(offset + 4));
        entity.setMPriority(cursor.getInt(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SelfTask entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SelfTask entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SelfTask entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
